language: emacs-lisp
# Emacs fails to build in container-based builds on Travis
# See https://github.com/travis-ci/travis-ci/issues/9061
# and https://github.com/moby/moby/issues/22801
sudo: required
dist: bionic
cache:
  - directories:
      # Cache stable Emacs binaries (saves 1min per job)
      - "$HOME/emacs/"
# Allow Emacs snapshot builds to fail and don’t wait for these as they can take
# a looooong time
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=emacs-snapshot
env:
  - EMACS_VERSION=emacs26
  - EMACS_VERSION=emacs-snapshot

before_install:
    # Emacs kelleyk PPA
  - sudo add-apt-repository -y ppa:kelleyk/emacs
  - sudo apt-get update
  - sudo apt install $EMACS_VERSION-nox
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1
  - export PATH="$HOME/bin:$PATH"
  - export EMACS=$EMACS_VERSION
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -f emacs-travis.mk install_cask
  - travis_retry sudo apt-get install -y fsharp

script:
  - make test
